### ISSUE TITLE
modern c++ #2 stream time

### ISSUE THREAD

**Issue by DamiXioR** [coders-school/modern-cpp#22]
MODERN C++ #2

Start 00:03:45
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=225s
Agenda 00:06:25
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=385s
default KEYWORD 00:07:18
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=438s
delete KEYWORD 00:15:00
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=900s
Exercise 00:22:06
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=1326s
Exercise solution 00:31:34
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=1894s
Exercise solution 00:34:30
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=2070s
final KEYWORD 00:35:55
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=2155s
override KEYWORD 00:40:25
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=2425s
Exercise 00:43:08
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=2588s
Exercise solution 00:47:28
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=2848s
Exercise solution 00:50:18
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=3018s
Exercise solution 00:53:26
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=3206s
Attributes 01:01:17
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=3677s
[[noreturn]] attribute 01:04:44
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=3884s
[[fallthrough]] attribute 01:05:23
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=3923s
[[nodiscard]] attribute 01:06:03
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=3963s
[[maybe_unused]] attribute 01:08:07
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=4087s
Assert and contract programming 1:09:08
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=4148s
[[deprecated]] attribute 01:12:58
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=4378s
Exercise 01:13:45
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=4425s
Lambdas repo link 1:15:00
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=4500s
Exercise solution 01:17:23
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=4643s
constexpr KEYWORD 01:21:51
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=4911s
constexpr VARIABLES 01:25:06
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=5106s
constexpr FUNCTIONS 01:28:31
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=5311s
constexpr FUNCTIONS RESTRICTIONS 01:31:25
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=5485s
constexpr CONSTRUCTOR 01:34:28
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=5688s
constexpr LAMBDA 01:35:14
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=5714s
constexpr IF 01:36:46
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=5806s
constexpr IF IN SFINAE 01:38:49
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=5929s
Exercise 01:41:31
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=6091s
Break 01:44:13
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=6253s
After break 02:03:33
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=7413s
Exercise solution 02:05:30
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=7530s
noexcept KEYWORD 02:14:51
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=8091s
noexcept OPERATOR 02:17:08
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=8228s
noexcept KEYWORD c++17 02:18:46
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=8326s
Exercises 02:19:17
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=8357s
Data structure aligment 02:25:51
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=8751s
alignas KEYWORD 02:25:53
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=8753s
alignof KEYWORD 02:28:46
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=8228s
Exercise 02:33:20
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=8926s
Structured bindings 02:33:27
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=9207s
Exercise 02:34:57 
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=9297s
Other usefull features 02:35:35
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=9335s
Nested namespace definitions 02:35:35
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=9335s
Class template argument deduction 02:36:17
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=9377s
Selection statements with initializer 02:37:42
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=9462s
Overview 02:41:00
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=9660s
Repetition 02:41:39
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=9699s
C++ quirks 02:43:40
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=9820s
Pre – test 02:44:50
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=9890s
Homework 02:52:02
https://www.youtube.com/watch?v=Aqxo4Y-vwAs&t=10322s

**Comment by ziobron** [comment]
thanks, added. Time before caption require less manual job from my side ;)

**Comment by ziobron** [comment]
5 XP za utworzenie spisu treści do lekcji na YouTube (4069) added
